---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hello-life
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/kevindarzini/hello-life
