---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: life-app
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: hello-app
  targetNamespace: life
  timeout: 2m0s
  wait: true
