---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hello-life-source
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com./kevindarzini/hello-life.git
